### ISSUE TITLE
can we combine two functions?

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/comparing-sentiment#5]
wondering if we can combine two functions in cases where we pass the file name and then read the file, e.g.:

What is presently:

```{r}
tar_target(ss_scale_file, here::here("data-sentiment", "sentistrength_scale.txt"), format="file"),
tar_target(ss_scale_data, read.table(ss_scale_file, sep="\t", header = T, quote="")),
```

change to:

```{r}
tar_target(ss_scale_file, read.table(here("data-sentiment", "sentistrength_scale.txt"), sep="\t", header = T, quote=""), format="file"),
````

This [part of the manual](https://wlandau.github.io/targets-manual/files.html) seems to suggest this is possible (that we can still tell {targets} that this function loads a file). Thanks for input when you get chance!

**Comment by jrosen48** [comment]
Hm, I'm a bit confused by this, also from the manual, which seems to suggest you _cannot_ combine the above two functions into one function:

> Targets with the "file" format are called dynamic files, and these targets are unusual because their return values do not get saved in the _targets/objects/ folder. Rather, they expect you to return a character vector files and directories, which gets stored in the _targets/meta spreadsheet, and then targets watches the data at those paths for changes.

**Comment by jrosen48** [comment]
But does [section 4.3 of the manual](https://wlandau.github.io/targets-manual/files.html) suggest that we could create an imported function that both loads (or saves) the file, but still returns a file path.

**Comment by conradborchers** [comment]
Good point! You can save targets objects as external files and return their path, but then you need to re-read in that path in order to reference these objects inside the pipeline. In short: If you want to keep referencing data frames without an additional read-in step, you need to make these two steps. At some points it makes sense to save targets objects externally but I think its not the best idea to do it at all steps. Lastly, I think that `tar_target(ss_scale_file, read.table(here("data-sentiment", "sentistrength_scale.txt"), sep="\t", header = T, quote=""), format="file"),` would not work since a data object would be returned by the type expects a path/string. Will touch on that in the meeting later today!

**Comment by jrosen48** [comment]
This all makes sense to me. Thanks for unpacking the details to explain.
________________________________
